---
- hosts: omero_hosts
  roles:
  - role: openmicroscopy.omero-server
    postgresql_users_databases:
    - user: omero
      password: "{{ omero_dbpassword }}"
      databases: [omero]
  - role: hajaalin.truststore
