---
  test: omero_var_test
  omero_selinux_setup: True
  omero_release: 5.2.7
  #omero_release: v5.3.0-m6
  omero_upgrade: True

  omero_dbpassword: "{{ vault_omero_dbpassword }}"

  omero_server_config:
    omero.ldap.config: "true"
    omero.ldap.urls: "{{ vault_omero_ldap_urls }}"
    omero.ldap.username: "{{ vault_omero_ldap_username }}"
    omero.ldap.password: "{{ vault_omero_ldap_password }}"
    omero.ldap.base: "ou=people,dc=helsinki,dc=fi"
    omero.ldap.user_mapping: "omeName=uid,firstName=givenName,lastName=sn,email=mail"
    omero.ldap.user_filter: "(memberOf=cn=grp-lmu-users,ou=groups,dc=helsinki,dc=fi)"
    #omero.ldap.user_filter: "(memberOf=cn=grp-hajaalin-test1,ou=groups,dc=helsinki,dc=fi)"
    #omero.ldap.user_filter: "(objectClass=person)"
    omero.ldap.new_user_group: "lmu-customers"
    #omero.ldap.sync_on_login: "false"
    omero.security.trustStore: "{{ truststore_path }}"
    omero.security.trustStorePassword: "{{ truststore_password }}"
    #omero.jvmcfg.heap_size.blitz: "3G"

  # Trust store certificates
  truststore_dir: "{{ omero_basedir }}/truststore"
  truststore_password: "{{ vault_omero_trust_store_passwd }}"
  truststore_owner: "omero"
  truststore_group: "omero"
  truststore_cert_url_block: |
    https://www.digicert.com/CACerts/DigiCertAssuredIDRootCA.crt
    http://www.terena.org/activities/tcs/repository/AddTrust_External_CA_Root.pem
    http://www.terena.org/activities/tcs/repository/UTN-USERFirst-Hardware.pem
    http://www.terena.org/activities/tcs/repository/TERENA_SSL_CA.pem
    http://www.terena.org/activities/tcs/repository/TERENA_eScience_SSL_CA.pem
